FROM node:10-alpine as builder

WORKDIR /app

COPY package*.json /app/

RUN npm ci --silent
RUN npm install react-scripts -g --silent
COPY . /app/

RUN npm run build

# production environment

FROM nginx:stable-alpine
COPY --from=builder /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"] 