version: '3.7'

services:
  app:
    image: netflux:dev
    build: ./
    expose:
      - 3000
    ports:
      - 3000:3000
    volumes:
      - ./src/:/app/src/
      - ./public/:/app/public/
    command: npm start
    environment:
      - CHOKIDAR_USEPOLLING=true  
