version: '3.7'

services:
  app:
    image: netflux:dev
    container_name: netflux
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 3000
    ports:
      - 3000:3000
    volumes:
      - ./src/:/app/src/
      - ./public/:/app/public/
    environment: 
      - REACT_APP_apiKey=${REACT_APP_apiKey}
      - REACT_APP_authDomain=${REACT_APP_authDomain}
      - REACT_APP_projectId=${REACT_APP_projectId}
      - REACT_APP_storageBucket=${REACT_APP_storageBucket}
      - REACT_APP_messagingSenderId=${REACT_APP_messagingSenderId}
      - REACT_APP_appId=${REACT_APP_appId}
    command: npm start
    environment:
      - CHOKIDAR_USEPOLLING=true  
