version: '3.7'

services:
  app:
    image: netflux:dev
    container_name: netflux
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 3000
    ports:
      - 3000:3000
    volumes:
      - ./src/:/app/src/
      - ./public/:/app/public/
    command: npm start
    environment:
      - CHOKIDAR_USEPOLLING=true  
