version: '3.7'

services:
  app:
    container_name: netflux-prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    environment: 
      - REACT_APP_apiKey=${REACT_APP_apiKey}
      - REACT_APP_authDomain=${REACT_APP_authDomain}
      - REACT_APP_projectId=${REACT_APP_projectId}
      - REACT_APP_storageBucket=${REACT_APP_storageBucket}
      - REACT_APP_messagingSenderId=${REACT_APP_messagingSenderId}
      - REACT_APP_appId=${REACT_APP_appId}
    ports:
      - '8877:80'    